### ISSUE TITLE
random nonblocking pool is initialized

### ISSUE THREAD

**Issue by warmc** [conanwhf/RaspberryPi-script#2]
你好，我用你的脚本备份树莓派3B，系统是官方的2017-04-10-raspbian-jessie-lite.img，备份成功，用Win32DiskImager 写入到新的SD卡后，启动树莓派，卡在“random nonblocking pool is initialized” 这一句，上网搜索了一下，也是无结果。希望能帮助一下我。谢谢

**Comment by conanwhf** [comment]
有更多的log吗？

**Comment by warmc** [comment]
@conanwhf ，我只能拍屏幕照，不知道怎么给你看。

**Comment by conanwhf** [comment]
😓你的终端不能复制的吗？你这么给一句log，都不知道是哪里打印的，没办法给你建议

发自我的 iPhone

**Comment by xty19** [comment]
![qq 20170525154354](https://cloud.githubusercontent.com/assets/9359167/26440741/4628053e-4160-11e7-9116-ed4bc6fec1ac.jpg)
random nonblocking pool is initialized”
@conanwhf

**Comment by xty19** [comment]
@conanwhf 我插上U盘后，
运行你的脚本，提示
mount:/dev/sdd1 is already mounted or /mnt busy
           /dev/sdd1 is already mounted on /media/pi/BOOT
mount fail.exit now.

**Comment by xty19** [comment]
我觉得可能是fat32 盘不够大， 因为我插入sd卡，进行img生成，最后img文件大小4000M+

**Comment by conanwhf** [comment]
有可能，反正肯定是文件backup/restore不全，你看你之前传的图，在很早就有error了，无法load某些库文件

**Comment by conanwhf** [comment]
你应该是之前跑过这个脚本，中途中断了，umount一下就好

**Comment by szhansen** [comment]
"random: nonblocking pool is initialized"

和楼主一样，反复多次 都是打印这句，楼主解决了吗 ？

**Comment by warmc** [comment]
我的问题解决了。下面描述一下，如果情况跟我一样的可以参考。
1.我是将SD卡A上面的系统进行备份成img；
2.将备份的img使用工具写入到SD卡B上面
我的问题就在于：备份后的img里面 /boot/cmdline.txt；/etc/fstab 这两个文件中使用了SD卡A的PARTUUID。将这两个文件中的PARTUUID修改成SD卡B的PARTUUID就可以了。贴一下获取PARTUUID命令：
sdCardB=/dev/sda1
blkid -o export ${sdCardB} | grep PARTUUID

**Comment by szhansen** [comment]
@warmc 试过了，手动修改 PARTUUID后，可以正常启动了

**Comment by szhansen** [comment]
官网发布的 img 可以烧录进任何sd卡是怎么实现的 ？
2017-04-10-raspbian-jessie-lite.img
这个版本第一次启动会 自动 resize 分区大小重启，貌似是这里做了什么手脚，
我在/boot/cmdline.txt内配置启动resize，开机后也重启提示会重新分区，但实际没起作用

**Comment by conanwhf** [comment]
可以重新获取UUID替换文本啊。我估计这个问题是因为官方release的root=XXXX以前是设备节点，后来才改成UUID的，所以以前我测过没问题。
这个问题等过些天有空我改一下脚本，应该可以解决
